# This is a config for E2B sandbox template.
# You can use template ID (zwh4f8kyh7ne10cp8r3d) or template name (vibe-nextjs-zaman2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-zaman2") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-zaman2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-zaman2')

team_id = "f0f396ee-f831-40b1-9766-3e2f6f7f1512"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-zaman2"
template_id = "zwh4f8kyh7ne10cp8r3d"
